name: '[📊] CI'

concurrency:
  cancel-in-progress: true
  group: ci-booklib-app-${{ github.ref }}

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - synchronize
env:
  BASE_URL: http://127.0.0.1:3001
  USER_DB_PATH: ./booklib.json

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Run typecheck
        run: yarn lint:ts

      - name: Run ESLint
        run: yarn lint:js

      - name: Run Prettier
        run: yarn lint:prettier

      - name: Run tests
        run: yarn test
