name: '[🧪] E2E Tests'
on:
  push:
    branches: [main]

env:
  BASE_URL: http://127.0.0.1:3001
  USER_DB_PATH: ./booklib.json

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: Cache Playwright Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-chromium
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: yarn playwright install chromium --with-deps

      - name: Build app
        run: yarn build

      - name: Run Playwright tests
        run: yarn test:e2e
        env:
          CI: true
