name: '[🧪] E2E Tests'
on:
  push:
    branches: [main]

env:
  BASE_URL: http://127.0.0.1:3001
  USER_DB_PATH: tests/setup/booklib-test.json

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile

      - name: Cache Playwright Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-chromium
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: yarn playwright install chromium --with-deps

      - name: Build app
        run: yarn build

      - name: Start Nuxt preview server
        run: yarn preview --port 3001 --hostname 0.0.0.0 &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001 --timeout 60000

      - name: Run Playwright tests
        run: yarn test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
